name = "yaml-config-merger-tool"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist/yaml-config-merger-tool/browser"

[env.production]
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist/yaml-config-merger-tool/browser"